### ISSUE TITLE
[generate_toppra_trajectory.py] Python3 Error

### ISSUE THREAD

**Issue by lmark1** [larics/topp_ros#1]
When running [generate_toppra_trajectory.py](https://github.com/larics/topp_ros/blob/master/scripts/generate_toppra_trajectory.py) in Python 3 it fails with the following error:
```bash
generate_toppra_trajectory.py", line 38
    print " "
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(" ")?
```

**Comment by fpetric** [comment]
maybe try this https://docs.python.org/3/library/2to3.html
